### ISSUE TITLE
Cannot deserialize into `Report` what has been produced by `cargo-audit`

### ISSUE THREAD

**Issue by woshilapin** [rustsec/rustsec#449]
I'm trying to parse back a JSON produced through `cargo-audit:v0.15.2`. Here is a very simple project to reproduce the problem (note that `cargo-audit` must already be installed on the system).

# `Cargo.toml`

```toml
[package]
name = "audit-deserialize"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsec = { version = "0.24", features = ["dependency-tree"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# A few dependencies only to generate errors
nix = "=0.19.1"
slice-deque = "=0.3.0"
```

# `src/main.rs`

```rust
fn main() {
    let mut cmd = std::process::Command::new("cargo");
    cmd.arg("audit")
        .arg("--json")
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null());
    let stdout = cmd.spawn().unwrap().stdout.unwrap();
    let report = serde_json::from_reader::<_, rustsec::Report>(stdout).unwrap();
}
```

# Result

Running the above program panics with the following message.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"linux\", expected a borrowed string", line: 1, column: 1933)', src/main.rs:8:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
