### ISSUE TITLE
`cargo audit` creates a `./~/.cargo/advisory-db` directory

### ISSUE THREAD

**Issue by thanethomson** [rustsec/rustsec#585]
Running `cargo audit` on [tendermint-rs](https://github.com/informalsystems/tendermint-rs) locally creates a `~/.cargo/advisory-db` directory within the repository directory itself - it doesn't seem to be resolving the `~` path correctly.

```bash
> cargo audit
# ...

> ls
'~'     Cargo.lock   CHANGELOG.md   CONTRIBUTING.md   img       light-client      light-client-verifier   pbt-gen   README.md    rpc       target       test      TODO
 abci   Cargo.toml   config         docs              LICENSE   light-client-js   p2p                     proto     release.sh   std-ext   tendermint   testgen   tools

> ls ./\~/.cargo/advisory-db
CODE_OF_CONDUCT.md  CONTRIBUTING.md  crates  EXAMPLE_ADVISORY.md  HOWTO_UNMAINTAINED.md  LICENSE.txt  README.md  rust  support.toml
```

Running this on Ubuntu 20.04.4 LTS.

**Comment by tarcieri** [comment]
That's odd. `rustsec` uses the `home` crate to find the `~/.cargo` directory:

https://github.com/brson/home

The relevant code is here:

https://github.com/rustsec/rustsec/blob/2ea0ddc/rustsec/src/repository/git/repository.rs#L30-L37

**Comment by thanethomson** [comment]
Very weird. I've tried looking for environment variables that could perhaps be interfering in the background, but other than a `PATH` variable I have no other env vars mentioning `~/.cargo`

**Comment by rmg** [comment]
If you use the [`audit.toml.example`](https://github.com/rustsec/rustsec/blob/34fd7dc2247e5491684e8d1719b3658ac61f8e94/cargo-audit/audit.toml.example) as `.cargo/audit.toml` as-is then it would cause this behaviour.

It contains a `path = "~/.cargo/advisory-db"` which would be interpreted as a literal path:

```toml
# Advisory Database Configuration
[database]
path = "~/.cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true # Perform a `git fetch` before auditing (default: true)
stale = false # Allow stale advisory DB (i.e. no commits for 90 days, default: false)
```

`~` is normally supposed to be resolved by the shell, so the default is _equivalent_ to `~/.cargo/advisory-db`, but isn't literally that path since `~`, like a shell.

If you do `cargo audit --db ~/.cargo/advisory-db` it will work as desired, but if you do `cargo audit --db "~/.cargo/advisory-db"` or `cargo audit --db '~/.cargo/advisory-db'` it will prevent the shell from resolving `~` and you'll get the observed behaviour.
