### ISSUE TITLE
Database originated CVSS fields

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#713]
Following-up from: https://github.com/rustsec/rustsec/pull/682

We just imported a lot of CVSS classifications from NVD and I think this is covered by a CC-BY-4.0 license.

But this deserves it's separate issue - 

How should we name the field - it should work like the `[affected] functions` field I think

This given that other databases identify multiple sources for the thing and I think we should improve our presentation here as welll.

Or:

```toml
[origin]
text = ["GHSA", ".."]
cvss = { "NVD" = "xxx.." }
cvss = { "RUSTSEC" = "xxx.." }
```
