### ISSUE TITLE
cargo-audit fails on sparse registries

### ISSUE THREAD

**Issue by waltronix** [rustsec/rustsec#868]
`cargo-audit` fails to parse `Cargo.lock` files with when package source starts with `sparse+`.

Internally, we are using a sparse private registry as proxy for crates-io.

When trying to run `cargo-audit` I get the following error.

```
error: not found: Couldn't load Cargo.lock: I/O operation failed: parse error: parse error: unsupported source protocol: sparse for key `package.source` at line 366 column 1
```

I could reproduce the issue with a minimal sample where I use the following `config.toml`

```toml
[registries.sparse_sample]
index = "sparse+https://index.crates.io/"
```

with a `Cargo.toml`

```toml
[package]
name = "sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {version = "0.1", registry = "sparse_sample"}
```

In `Cargo.lock`, the package definitions look like:

```toml
[[package]]
name = "log"
version = "0.1.10"
source = "sparse+https://index.crates.io/"
checksum = "527343c5c05a389bbd6818d495e5d7577feb4dd51ca698c158edabf398a3a4bc"
dependencies = [
 "regex",
]
```

The issue already seems to be fixed in `cargo-lock`, but `cargo-audit` does not already use the fixed version here.
