### ISSUE TITLE
`cargo audit` should not report withdrawn reports

### ISSUE THREAD

**Issue by rhysd** [rustsec/rustsec#920]
## Repro

```sh
git clone https://github.com/rhysd/hgrep.git && cd ./hgrep
git reset --hard 567880f336044ad21625c4f5b7acbd0ed4a8e44f
cargo audit
```

## Actual behavior

`cargo audit` reoprted:

```
Crate:         dirs
Version:       4.0.0
Warning:       unmaintained
Title:         dirs is unmaintained, use dirs-next instead
Date:          2020-10-16
ID:            RUSTSEC-2020-0053
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 4.0.0

Crate:         dirs
Version:       5.0.1
Warning:       unmaintained
Title:         dirs is unmaintained, use dirs-next instead
Date:          2020-10-16
ID:            RUSTSEC-2020-0053
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 5.0.1
```

In addition, the advice 'dirs is unmaintained, use dirs-next instead' is not correct because now `dirs` is more actively maintained than `dirs-next` actually.

## Expected behavior

`dirs` should not be reported as maintained crate because it is actually [actively maintained](https://github.com/dirs-dev/dirs-rs/activity).

In the advisory DB, [RUSTSEC-2020-0053](https://github.com/rustsec/advisory-db/blob/main/crates/dirs/RUSTSEC-2020-0053.md) is withdrawn on 2021-04-19.

```toml
[advisory]
id = "RUSTSEC-2020-0053"
package = "dirs"
date = "2020-10-16"
informational = "unmaintained"
url = "https://github.com/dirs-dev/dirs-rs"
withdrawn = "2021-04-19"

[versions]
patched = []
```

`cargo audit` should not show the withdrawn report as vulnerability.
