### ISSUE TITLE
Incosistency between config file and CLI

### ISSUE THREAD

**Issue by daxpedda** [rustsec/rustsec#991]
If I use `cargo audit --deny warnings` it throws an error on yanked crates.

But if I use:
```toml
[output]
deny = ["warnings"]
quiet = false
```
it won't. It will continue to only throw a warning.

Curiously if I use `deny = ["yanked"]` it will correctly throw an error on yanked crates.

Used v0.18.1.
